### ISSUE TITLE
Funky button behavior on homepage

### ISSUE THREAD

**Issue by ericschultz** [alterm4nn/ChronoZoom#1376] opened 2014-12-16 17:05 UTC
I've noticed that on the homepage, the buttons for featured content sometimes link to the homepage, not the expected content. It's not entirely clear to me but I thought I'd put this down in the issues so people knew about them.

I'm running Mozilla Firefox 36.0a2 on Windows 8.1

**Comment by NeilCresswell** [comment] 2015-01-27 21:50
Hi Eric,

A quick update: I've submitted a pull request today that should hopefully address this issue. It should go live in the next couple of days.

Regards,
Neil.

**Comment by alterm4nn** [comment] 2015-02-24 10:25
@ericschultz can you confirm that issue is fixed now? I cannot reproduce it anymore

**Comment by ericschultz** [comment] 2015-02-24 16:36
I've tested it again. I don't remember exactly how the problem manifested but I'm not noticing it now.

**Comment by alterm4nn** [comment] 2015-02-24 18:24
Very good, thanks!

**Closed** 2015-02-24 18:24 UTC
Labels: bug, no repro
